version: 2.1
jobs:
  build-mac:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Create Workspace Directory
          command: mkdir -p workspace/build-mac
      - run:
          name: Build for macOS
          command: |
            brew update
            brew install cmake
            mkdir -p workspace
            cd workspace
            mkdir -p build-mac
            cd build-mac
            cmake ../..
            make
      - persist_to_workspace:
            root: workspace
            paths: 
              - build-mac

  build-windows:
    docker:
      - image: mcr.microsoft.com/windows/servercore:ltsc2019
    steps:
      - checkout
      - run:
          name: Create Workspace Directory
          command: mkdir workspace/build-windows
      - run:
          name: Build for Windows
          command: |
            mkdir C:\build-windows
            cd C:\build-windows
            cmake C:\Builded
            cmake --build .
      - persist_to_workspace:
          root: workspace
          paths:
            - build-windows

  deploy-mac:
    machine: true
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Deploy to HWorld_mac
          command: |
            pwd
            ls
            cd workspace
            ls
            git clone https://esNaglfar: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@github.com/esNaglfar/HWorld_mac.git
            
            cd HWorld_mac

            cp -r ../build-mac/* .
            git config user.name "esNaglfar"
            git config user.email "es.naglfar@gmail.com"
            git add .
            git commit -m "Deploy macOS build"
            git remote set-url origin https://esNaglfar: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@github.com/esNaglfar/HWorld_mac.git

            git push origin main

  deploy-windows:
    machine: true
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Deploy to HWorld_win64
          command: |
            cd /workspace/build-windows
            git clone https://github.com/ваш_пользователь/HWorld_win64.git
            cd HWorld_win64
            git config user.name "Your Name"
            git config user.email "your@email.com"
            git add .
            git commit -m "Deploy Windows build"
            git push origin main

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-mac
      - build-windows
      - deploy-mac:
          requires:
            - build-mac
      - deploy-windows:
          requires:
            - build-windows
