version: 2.1
jobs:
  build:
    macos:
      xcode: 12.5.1 # Версия Xcode
    steps:
      - checkout # Клонировать репозиторий
      - run:
          name: Build
          command: |
            brew update
            brew install cmake
            mkdir build
            cd build
            cmake ..
            make
            cd ..

  deploy:
    docker:
      - image: circleci/python:3.7 # Может потребоваться установить git
    steps:
      - checkout # Клонировать репозиторий
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Deploy to Hworld-mac repository
          command: |
            # Создать новый репозиторий и отправить туда результат
            git clone https://github.com/esNaglfar/Hworld-mac.git
            cd Hworld-mac
            git config user.email "es.naglfar@gmail.com"
            git config user.name "esNaglfar
            cp ../main .
            git add main
            git commit -m "Add compiled binary for MacOS"
            git push origin master
