version: 2.1
jobs:
  build:
    macos:
      xcode: 12.5.1 # Версия Xcode
    steps:
      - checkout # Клонировать репозиторий
      - run:
          name: Build
          command: |
            ls
            echo '-----'
            brew update
            brew install cmake
            mkdir build
            ls
            echo '-----'
            cd build
            ls
            echo '-----'
            cmake ..
            ls
            echo '-----'
            make
            ls
            echo '-----'
            cd ..
            ls
            echo '-----'

  deploy:
    docker:
      - image: circleci/python:3.7 # Может потребоваться установить git
    steps:
      - checkout # Клонировать репозиторий
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Deploy to Hworld-mac repository
          command: |
            # Создать новый репозиторий и отправить туда результат
            ls
            echo '-----'
            git clone https://github.com/esNaglfar/HWorld_mac.git
            echo '-----'
            ls
            cd HWorld_mac
            git config user.email "es.naglfar@gmail.com"
            git config user.name "esNaglfar
            cp ../build .
            git add main
            git commit -m "Add compiled binary for MacOS"
            git push origin master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
